# Generated by Django 3.2.9 on 2021-12-08 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_auto_20211208_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='equipo',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='estadio',
            old_name='anioFundacion',
            new_name='anioFund',
        ),
    ]
