# Generated by Django 3.2.9 on 2021-12-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_auto_20211208_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadio',
            old_name='dirección',
            new_name='direccion',
        ),
    ]
